sudo: required
services:
	- docker

before_install:
	- docker build -t tomaszbarwicki/react-test - f ./client/Dockerfile.dev ./client

script:
	- docker run tomaszbarwicki/react-test npm test -- --coverage

after_success:
	- docker build -t tomaszbarwicki/multi-client  ./client
	- docker build -t tomaszbarwicki/multi-nginx ./nginx
	- docker build -t tomaszbarwicki/multi-server ./server
	- docker build -t tomaszbarwicki/multi-worker ./worker

# Log in to the docker CLI

	- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# Push images to docker hub

	- docker push tomaszbarwicki/multi-client
	- docker push tomaszbarwicki/multi-nginx
	- docker push tomaszbarwicki/multi-server
	- docker push tomaszbarwicki/multi-worker
